### ISSUE TITLE
How to get this to work with terraform 0.10

### ISSUE THREAD

**Issue by tk8817** [squat/terraform-provider-vultr#1]
Seemingly 0.10 is not reading from the `.terraformrc` file :(

**Comment by squat** [comment]
@tk8817 it looks like it is a bug in upstream Terraform. A patch [0] was just merged into master 4 hours ago that fixes the issue [1]. If you run `go get -u github.com/hashicorp/terraform` you should be updated and reading from `.terraformrc` will work again.

[0] https://github.com/hashicorp/terraform/pull/15769
[1] https://github.com/hashicorp/terraform/issues/15705

**Comment by tk8817** [comment]
Thanks so much! I am hoping to see this become part of the official providers!

**Comment by squat** [comment]
@tk8817 thanks for the kind words! I just wanted to make sure, did updating Terraform fix the issue for you?

**Comment by tk8817** [comment]
@squat - yes, I was able to get it to work. 

Tried with 
1) create binary from master branch source
2) replacing binary installed from brew
