### ISSUE TITLE
[Feature] Import Existing Resources

### ISSUE THREAD

**Issue by tk8817** [squat/terraform-provider-vultr#13]
Hey @squat, 

I have been working on building a set of modules for this provider to put on the terraform registry. When I went to get some support on the Terraform Gitter, I got heckled for not having importer functionality. I actually was not even aware of it until that conversation.

What are your thoughts on it? 
https://www.terraform.io/docs/import/usage.html

I was thinking of having a crack if it is something other people thing we need.

**Comment by squat** [comment]
Firstly, thanks for working on modules for this provider! There is another issue open asking for importer functionality: https://github.com/squat/terraform-provider-vultr/issues/11.

I am *all* for adding import support. It really should not be difficult at all. Please take a swing at it if you like. I'll also run some tests on my end.

**Comment by squat** [comment]
@tk8817 I'm closing this now that support for importing all existing resources, most notably instances, is implemented. :tada:
