### ISSUE TITLE
Add support for snapshots

### ISSUE THREAD

**Issue by dradtke** [squat/terraform-provider-vultr#15]
Vultr's API allows you to create servers from an existing snapshot by using OS ID 164 ("Snapshot") and by specifying a snapshot id. Choosing the correct OS ID is easy, but this provider doesn't appear to support specifying a snapshot id.

**Comment by squat** [comment]
@dradtke Thanks for pointing this out. I just added a new commit that introduces support for both searching for and specifying snapshots, as well as examples for both: c85bd5d63c3bfaabddc397bd3c084def25359b87.

I'll close this issue for now. Please re-open it if you have any issues.
