### ISSUE TITLE
Error: vultr_ssh_key.squat: 1 error(s) occurred:

### ISSUE THREAD

**Issue by ZoeyCluff** [squat/terraform-provider-vultr#18]
just installed your provider and when I try to terraform plan one of your examples it's erroring out on:

`* vultr_ssh_key.squat: file: open /Users/zoeycluff/lserven.ssh: no such file or directory in:

${file("~/lserven.ssh")}
`
where do I adjust where my ssh key is located?

**Comment by squat** [comment]
@ZoeyCluff, you need to modify the line that specifies the file path to your SSH key. In the basic example, that line would be: https://github.com/squat/terraform-provider-vultr/blob/master/examples/basic/example.tf#L76

Depending on where your key is located, that may mean changing the line to something like:
```
  public_key = "${file("~/.ssh/id_rsa.pub")}"
```

**Comment by squat** [comment]
@ZoeyCluff I'm closing this for now. Please re-open if you continue to have problems.
