### ISSUE TITLE
Changing or Removing the default IP forces the whole domain to be recreated

### ISSUE THREAD

**Issue by jdmulloy** [squat/terraform-provider-vultr#28]
If you want to change the IP of the apex A record of a domain this plugin will tear down the whole domain and recreate it. This is unnecessary and could result in downtime. As far as I can tell the Vultr API doesn't care about the IP you give the create_domain api call, after you've created the domain. It seems they just want an IP so they can make the apex record for you. They also annoyingly create MX records for you. The domain object should probably not force a new resource when this IP changes. Being able to refer to a record resource might be useful, although may be tricky to implement.

**Comment by squat** [comment]
This is a known issue. It’s an implementation detail to circumvent a deficiency of the Vultr API not assigning an ID to DNS records. I’ll investigate a solution.

**Comment by squat** [comment]
@jdmulloy the solution was actually easier than expected and leveraged a concept already used in another part of the repo :tada: . Commit 4834b87ea4284cf724045c6d65af9cc0bc4e3fcb closes this issue. Please give it a whirl and we can reopen this if it continues to be an issue.
