### ISSUE TITLE
Bare Metal resources

### ISSUE THREAD

**Issue by lgierth** [squat/terraform-provider-vultr#29]
Vultr recently started rolling our Bare Metal boxes: https://www.vultr.com/pricing/baremetal/

Unfortunately it comes with a new separate API: https://www.vultr.com/api/#baremetal

**Comment by squat** [comment]
@lgierth The main limitation for supporting bare metal resources is getting support for the new API into github.com/jamesclonk/vultr, which is the Vultr API library that this project depends on. I took a look at the bare metal API and it is extremely similar to the existing server API, so it should be very straightforward to port much of the existing code. In addition, the library maintainer is receptive to PRs and has always merged extensions and fixes needed for this provider quite speedily.

**Comment by squat** [comment]
@lgierth I now have full support for bare metal resources implemented. Updating this repo is just waiting for https://github.com/JamesClonk/vultr/pull/55 to merge.

**Comment by squat** [comment]
@lgierth now that JamesClonk/vultr#55 has landed, I pushed 78a4f9618100bcdb0cc52182fb8f1bb4bb9a488d. This commit adds support for managing and importing bare metal resources: bare metal servers and plans. Let me know if you're using this feature and have any issues.
