### ISSUE TITLE
Add firewall group as data source

### ISSUE THREAD

**Issue by tk8817** [squat/terraform-provider-vultr#3]
This would allow folks to provision their firewalls as a seperate service and then depend on them for instance creation terraform files.

**Comment by squat** [comment]
@tk8817 This is a good point. We really need data sources for every resource whose ID is not a human friendly value, e.g. a domain whose ID is the domain name; this mean pretty much all resources need data sources. I just added db218cb, which adds the firewall group data source. In vultr, firewall groups are not named but do have descriptions. This data source allows you to filter data sources by description and also to search for them using a `description_regex`. Please re-open if this does not address your need.
