### ISSUE TITLE
How do we assign an IPv6 address to a server?

### ISSUE THREAD

**Issue by prawadhwani** [squat/terraform-provider-vultr#41]
Have tried setting the ipv6 flag
`ipv6        = true`
but its 0,
```
ipv6:                 "" => "true" (forces new resource)
ipv6_address.#:       "0" => <computed>
```
Is this supported? If so, how do we assign one?

**Comment by squat** [comment]
@prawadhwani thanks for filing this. I am not able to recreate this problem. Looking at the Vultr API docs, it seems that IPv6 addresses depends on availability [0], so it may be specific to regions. I am able to create an instance and output it's IPv6 address with the following example configuration:

```hcl
// Find the ID of the Frankfurt region.
data "vultr_region" "frankfurt" {
  filter {
    name   = "name"
    values = ["Frankfurt"]
  }
}

// Find the ID for a starter plan.
data "vultr_plan" "starter" {
  filter {
    name   = "price_per_month"
    values = ["5.00"]
  }

  filter {
    name   = "ram"
    values = ["1024"]
  }
}

// Find the OS ID for Ubuntu.
data "vultr_os" "ubuntu" {
  filter {
    name   = "name"
    values = ["Ubuntu 18.04 x64"]
  }
}

// Create a Vultr virtual machine.
resource "vultr_instance" "ubuntu" {
  name      = "ubuntu"
  region_id = "${data.vultr_region.frankfurt.id}"
  plan_id   = "${data.vultr_plan.starter.id}"
  os_id     = "${data.vultr_os.ubuntu.id}"
  ipv6      = true
}

// Output all of the virtual machine's IPv6 addresses to STDOUT when the infrastructure is ready.
output ip_addresses {
  value = "${vultr_instance.ubuntu.ipv6_address}"
}
```
This produces the following example output:
```
Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

ip_addresses = [
    2001:19f0:6c01:162c:5400:01ff:fe92:7d2c
]
```

Can you post your configuration that replicates the issue?

[0] https://www.vultr.com/api/#server_create: `enable_ipv6 string (optional) 'yes' or 'no'.  If yes, an IPv6 subnet will be assigned to the machine (where available)`

**Comment by squat** [comment]
@prawadhwani closing for now. Please re-open if you still have this issue and post your configuration to replicate the issue :+1:
