### ISSUE TITLE
Mismatched Cidr Notation

### ISSUE THREAD

**Issue by marknet15** [squat/terraform-provider-vultr#43]
Hi,

First off great work on this plugin, just started using it for an internal project for which it works great.

Only issue I've noticed is that when creating a new network in Vultr in this instance "192.168.1.0/27" (changed from /28) the number gets increased by 1 so /27 becomes /28.

Is this something that could be looked into ?

![image](https://user-images.githubusercontent.com/14127638/45263823-04ae7100-b429-11e8-8a81-ad4c5ef6ae69.png)

**Operating System:** Windows 10
**Terraform version:** v0.11.8
**Plugin version:** latest

If you need anything further, then please let me know!

Best Regards,

Mark Woolley

**Comment by marknet15** [comment]
Please ignore me, I spent a while trying to work out why this was happening and its just user error on my part (just dawned) sorry and again great work on the plugin!

**Comment by squat** [comment]
Thanks for the kind words. I’m glad to got it sorted it out!
