### ISSUE TITLE
Enabling Autobackups

### ISSUE THREAD

**Issue by grant-veepshosting** [squat/terraform-provider-vultr#45]
The Vultr choice for 'autobackups' seems to be a boolean, can this be added to the vultr_instance type please so we can have auto backups?

**Comment by squat** [comment]
@grant-veepshosting thanks for the suggestion! Commit c4d4280dd0a322a094966311e83b22d0b12bbec3 adds this functionality to the provider. You can try the feature now by building the provider from source using `
go get -u github.com/squat/terraform-provider-vultr` (I'll cut a new release soon too). Please give it a try and re-open this issue if there are any problems.

**Comment by grant-veepshosting** [comment]
@squat I have tested this, and it works as expected - thanks!

Although I can't see it in the upstream API library you're using (boo!) it seems the Vultr API will let us manage some additional features including

When to run: Automatic backups can be configured to run daily, every other day, weekly, or monthly.
Defaults to Weekly each Thursday at 20:00 UTC.

The time of day, day of week/month that the backup occurs is configurable. Defaults to 8pm, it'd be nice to be able to adjust this programmatically.

Eg, for my current use case(s) we'd like to run "every other day" at 1pm UTC (timezone adjusted for what I need)...
