### ISSUE TITLE
“Provider doesn’t support data source” for resource vultr_startup_script

### ISSUE THREAD

**Issue by grant-veepshosting** [squat/terraform-provider-vultr#47]
When creating startup scripts at a different level in Terraform than the resources that will consume them, it would be enormously helpful to be able to lookup their IDs by Description or Name (as is possible for Firewall Groups and SSH Keys).

`resource "vultr_instance" "server" {
...
startup_script_id = "${data.vultr_startup_script.script1.id}"
}
data "vultr_startup_script" "script1" {
  filter {
    name   = "name"
    values = ["script1"]
  }
}
`

returns  “Provider doesn’t support data source”.

**Comment by squat** [comment]
@grant-veepshosting I just pushed a change that enables this feature. Please give it a shot and re-open the issue if there are any problems.

**Comment by grant-veepshosting** [comment]
This is very cool - thank you very much for the amazing turnaround time. I will test it within the next day and feedback if any issues are encountered.
