### ISSUE TITLE
Feature request - parameterise email notification on server creation

### ISSUE THREAD

**Issue by grant-veepshosting** [squat/terraform-provider-vultr#51]
According to Vultr support, their API supports a flag to disable emails at compute creation time.. this would be fantastic as a new feature for this plugin (as when pushing via API/Terraform, you can receive a _lot_ of emails in a short space of time).
```
notify_activate string (optional, default 'yes') 'yes' or 'no'. If yes, an activation email will be sent when the server is ready.
```

**Comment by squat** [comment]
@grant-veepshosting thanks for suggesting this fix! I implemented it in 59cbee04103def95719998f4729b0a5d68bdc8ef. It defaults to false, so we won't get emails unless explicitly enabled. Please give it a shot; if there are any issues, please re-open this issue.
