### ISSUE TITLE
Support adding/removing private networks without recreating the instance

### ISSUE THREAD

**Issue by mlazowik** [squat/terraform-provider-vultr#53]
Should be doable via https://github.com/JamesClonk/vultr/blob/master/lib/servers.go#L638

**Comment by squat** [comment]
great idea!

**Comment by squat** [comment]
This functionality should now be available in master thanks to https://github.com/squat/terraform-provider-vultr/commit/62b745009ca0628ff631027d1092040b71f7d14d. It will be in the next release of the plugin, though you can test it now if you install the plugin via git.

I'll close this for now but please comment back if you have issues with the feature.

**Comment by mlazowik** [comment]
Wow, that's a quick turnaround, thank you so much!
