### ISSUE TITLE
Expose MACs of private networks in instance resource 

### ISSUE THREAD

**Issue by mlazowik** [squat/terraform-provider-vultr#54]
Around here: https://github.com/squat/terraform-provider-vultr/blob/master/vultr/resource_instance.go#L276

The question is how to do this without breaking the API? Right know each private network value is just its IP, switching this to an object would mean existing configs ppl have wouldn't work.

**Comment by squat** [comment]
@mlazowik it’s unfortunate, but it’s ok to introduce a breaking API change. The API is not yet stable and this is exactly the right time to be introducing new features that help make this provider a fully featured plugin that is useful for all scenarios. If you’d like to have a go at writing the new feature, I would be more than happy to review it :)

**Comment by mlazowik** [comment]
Sure, I'll take a stab on that. I wonder how the state file will react to this, it should auto update on next `apply` (because it does `refresh` before `apply`), right?
