### ISSUE TITLE
API Rate Limit Exceeded Errors

### ISSUE THREAD

**Issue by bitshark** [squat/terraform-provider-vultr#8]
I keep getting API rate limit exceeded errors, even when setting parallism to 1 or 0... is there a way to configure this? 

```

* module.firewall2.vultr_firewall_rule.icmp_rule: vultr_firewall_rule.icmp_rule: 
Error getting firewall rule (c5a8d199/1): Rate limit reached - please try your request again later.  
Current rate limit: 2 requests/sec
```

**Comment by squat** [comment]
Thanks a lot for reporting this! Can you share an example .tf file you used to reproduce this error? I'd like to test it. We should also eventually have an integration test that tests for this rate limit error.

**Comment by squat** [comment]
Closing thanks to #17

**Comment by publicarray** [comment]
Hi, I just received the same error

```
* vultr_firewall_rule.ntp: vultr_firewall_rule.ntp: Error getting firewall rule (c639d718/6): Rate limit reached - please try your request again later.  Current rate limit: 2 requests/sec
````
I've installed via go so I'm current with the master branch

<details>
<summary>Example:</summary>
<pre><code>

resource "vultr_firewall_group" "rancher_dns_server" {
  description = "rancher-dns-server"
}

resource "vultr_firewall_rule" "ssh" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "0.0.0.0/0"
  protocol          = "tcp"
  from_port         = 22
  to_port           = 22
}

resource "vultr_firewall_rule" "docker" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "0.0.0.0/0"
  protocol          = "tcp"
  from_port         = 2376
  to_port           = 2376
}

resource "vultr_firewall_rule" "dot" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "0.0.0.0/0"
  protocol          = "tcp"
  from_port         = 853
  to_port           = 853
}

resource "vultr_firewall_rule" "dot_ipv6" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "::/0"
  protocol          = "tcp"
  from_port         = 853
  to_port           = 853
}

resource "vultr_firewall_rule" "dnscrypt_tcp" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "0.0.0.0/0"
  protocol          = "tcp"
  from_port         = 8443
  to_port           = 8443
}

resource "vultr_firewall_rule" "dnscrypt_tcp_ipv6" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "::/0"
  protocol          = "tcp"
  from_port         = 8443
  to_port           = 8443
}

resource "vultr_firewall_rule" "dnscrypt_udp" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "0.0.0.0/0"
  protocol          = "udp"
  from_port         = 8443
  to_port           = 8443
}


resource "vultr_firewall_rule" "dnscrypt_udp_ipv6" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "::/0"
  protocol          = "udp"
  from_port         = 8443
  to_port           = 8443
}

resource "vultr_firewall_rule" "doh" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "0.0.0.0/0"
  protocol          = "tcp"
  from_port         = 443
  to_port           = 443
}

resource "vultr_firewall_rule" "doh_ipv6" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "::/0"
  protocol          = "tcp"
  from_port         = 443
  to_port           = 443
}

resource "vultr_firewall_rule" "ntp" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "0.0.0.0/0"
  protocol          = "udp"
  from_port         = 123
  to_port           = 123
}

resource "vultr_firewall_rule" "ntp_ipv6" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "::/0"
  protocol          = "udp"
  from_port         = 123
  to_port           = 123
}

resource "vultr_firewall_rule" "munin" {
  firewall_group_id = "${vultr_firewall_group.rancher_dns_server.id}"
  cidr_block        = "0.0.0.0/0"
  protocol          = "tcp"
  from_port         = 4949
  to_port           = 4949
}

</code></pre>
</details>

**Comment by publicarray** [comment]
using ` -parallelism=1` works as a work around.

**Comment by gibsonje** [comment]
I'm also hitting this on firewall rules. It was after I refactored to use a for_each loop. I was wondering if that made it behave worse as far as hitting the api too fast. 

@publicarray 's suggestion of `parallelism=1` worked for me as a workaround.
