### ISSUE TITLE
internalizing fatih's structs

### ISSUE THREAD

**Issue by 979156** [squat/terraform-provider-vultr#82]
Hi @squat.
I am working on internalizing fatih's structs library following your guide with just copying whole package and modifying some.
I thought about switching current methods for interface as functions also, but there could be potential problems so suggesting this way.
Would it be okay for u to locate it at 'PROJECT_ROOT/lib/structs' in this way?

**Comment by squat** [comment]
@979156 thanks so much for taking the lead on this :) placing it in `/structs/structs.go` would be perfect, I think we can get away without an extra `lib` directory for now.

**Comment by squat** [comment]
Closed by #83
Thanks again for filing the issue and PR to fix it :)
