### ISSUE TITLE
Publish release with tf 0.12 support

### ISSUE THREAD

**Issue by OJFord** [squat/terraform-provider-vultr#84]
v0.12 is out of beta, and the readme here points to the releases page (and claims to support '0.9+') - so I think it'd be a good idea to publish a release with that support (which is in master) assuming it's fairly stable. If not, perhaps a note in the readme instead (>=0.9, <0.12)?

**Comment by squat** [comment]
Fixed by https://github.com/squat/terraform-provider-vultr/releases/tag/v0.1.10
:tada:
